services:
  app:
    build: .
    ports:
      - "9012:9012"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=documents
      - DB_USER=user
      - DB_PASSWORD=password

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: documents
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
